#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

## @package script elenco2
#  Script que roda o main
#  Trabalho desenvolvido para fins da disciplina de Otimização, feito por Roberta Samistraro Tomigian.

import elenco12
import sys

if __name__ == "__main__":
    # print('Arguments count: {}'.format(len(sys.argv)))
    # for i, arg in enumerate(sys.argv):
    #     print('Argument {}: {}'.format(i,arg))
    elenco12.main(len(sys.argv),sys.argv)